### ISSUE TITLE
Unstake specific number of tokens

### ISSUE THREAD

**Issue by Cryptogateway2020** [StorXNetwork/storx-staking-dapp#10]
Please give us option to unstake srx tokens instead of unstaking all now.
This is a good option to have if someone stake 5000 or 10000 srx per node.
Thanks

**Comment by rudreshsolanki97** [comment]
Hello, thank you for the suggestion. we cannot implement this right now as it would require us to make changes on the smart contract level which we are not planning to do.
Will mark as `wontfix` and be noted for further development.

**Comment by Cryptogateway2020** [comment]
Thanks Team... Great response.  Love it
