### ISSUE TITLE
Pinned / Naming functionality for Nodes on the network

### ISSUE THREAD

**Issue by itdxvida** [StorXNetwork/storx-staking-dapp#2]
Currently, the farmer.storx.io/staking site does not provide a way to pin all your nodes to the top of the list.  This will be a nice functionality to have to allow pinning of all your nodes, instead of scrolling through pages of nodes to find yours based on wallet.  Additionally, being able to name your nodes will be really nice. That way you can recognize your nodes based on the name vs the address attached to it.

**Comment by rudreshsolanki97** [comment]
Functionality added in commit [87fa7d329a](https://github.com/StorXNetwork/storx-staking-dapp/commit/87fa7d329afd9f8c7e138e3d2fb41e144ab636a2)
