### ISSUE TITLE
User Accounts and Node Tracking

### ISSUE THREAD

**Issue by ajnozari** [StorXNetwork/storx-staking-dapp#6]
It would be amazing if we could get user accounts where we register nodes.  Registration could be similar to how we "connect" nodes now to prove we have access, and wouldn't require storage of the keys, just the association.

This would enable us to get simple node metrics and provide a launch platform for the addition of other metrics and analytics.

**Comment by rudreshsolanki97** [comment]
we are working on a dashboard for node analytics which will be independent from the user account from storx.
